version: '3.5'

services:
  proxy:
    image: traefik:1.7.1-alpine
    command: --api --docker --docker.domain=rh-dev.eu
    ports:
      - '80:80'
      - '8000:80'
      - '8001:80'
      #  traefik dashbord
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - regiohelden
    labels:
      - 'traefik.port=8080'
    restart: always

networks:
  regiohelden:
    name: rh-dev.eu
    ipam:
      config:
        - subnet: 10.199.0.0/16        