version: '3.5'

services:
  proxy:
    image: traefik:2.1.1
    ports:
      - '443:443'
      - '80:80'
      - '8000:80'
      - '8001:80'
      - '8025:80'
      - '3000:80'
      - '9200:80'
      #  traefik dashbord
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic-traefik.toml:/dynamic-traefik.toml
      - ./traefik.toml:/traefik.toml
    networks:
      - regiohelden
    restart: always

networks:
  regiohelden:
    name: rh-dev.eu
    ipam:
      config:
        - subnet: 10.199.0.0/16
